mysql:
 host: "localhost"
 port: 3306
 user: "root"
 name: "minecraft"
 password: ""


kits:
 default:
  inventory-name: "test"
  permission: "test.permission"
  icon: "310 1 protection:4 unbreaking:3"
  cooldown: 10
  items:
  - "310 1 protection:4 unbreaking:3"
  - "311 1 protection:4 unbreaking:3"
  - "312 1 protection:4 unbreaking:3"
  - "313 1 protection:4 unbreaking:3"
  - "276 1 sharpness:5 unbreaking:3 fireaspect:2"
